/*Ejercicios Join y subconsultas:
Ejercicios Join
Ejercicio 1.a*/
SELECT CURSO.CURSO_ID,CURSO.CUPO_MAXIMO,PROFESOR.NOMBRE,HORARIO.DIA_SEMANA,HORARIO.HORA_INICIO,HORARIO.HORA_FIN
FROM (((((CURSO 
INNER JOIN PROFESOR ON PROFESOR.PROFESOR_ID = CURSO.PROFESOR_ID)
INNER JOIN CURSO_HORARIO ON CURSO.CURSO_ID = CURSO_HORARIO.CURSO_ID)
INNER JOIN SEMESTRE ON SEMESTRE.SEMESTRE_ID = CURSO.SEMESTRE_ID)
INNER JOIN HORARIO ON CURSO_HORARIO.HORARIO_ID = HORARIO.HORARIO_ID)
INNER JOIN ASIGNATURA ON ASIGNATURA.ASIGNATURA_ID = CURSO.ASIGNATURA_ID)
WHERE (SEMESTRE.ANIO=2008 AND SEMESTRE.PERIODO = 1 AND ASIGNATURA.NOMBRE = 'CALCULO 2');
/*Ejercicio 1.b*/
SELECT CURSO.CURSO_ID,CURSO.CLAVE_GRUPO,ASIGNATURA.NOMBRE
FROM ((ASIGNATURA
INNER JOIN CURSO ON ASIGNATURA.ASIGNATURA_ID = CURSO.ASIGNATURA_ID)
INNER JOIN ESTUDIANTE_INSCRITO ON CURSO.CURSO_ID = ESTUDIANTE_INSCRITO.CURSO_ID)
WHERE (ESTUDIANTE_INSCRITO.CALIFICACION IS NULL);
/*Ejercicio 2.a*/
SELECT *
FROM PROFESOR
NATURAL JOIN  CURSO
WHERE PROFESOR.APELLIDO_PATERNO = 'KRAUCE';
/*Ejercicio 2.b1*/
SELECT PROFESOR.PROFESOR_ID, PROFESOR.NOMBRE, PROFESOR.APELLIDO_PATERNO, PROFESOR.APELLIDO_MATERNO, CURSO.CLAVE_GRUPO 
FROM ((PROFESOR
INNER JOIN CURSO ON PROFESOR.PROFESOR_ID = CURSO.PROFESOR_ID)
INNER JOIN SEMESTRE ON CURSO.SEMESTRE_ID = SEMESTRE.SEMESTRE_ID)
INNER JOIN ASIGNATURA ON CURSO.ASIGNATURA_ID = ASIGNATURA.ASIGNATURA_ID
WHERE SEMESTRE.SEMESTRE_ID = 1 AND ASIGNATURA.NOMBRE = 'BASES DE DATOS';
/*Ejercicio 2.b2*/
SELECT PROFESOR_ID, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, CLAVE_GRUPO
FROM CURSO
NATURAL JOIN PROFESOR
NATURAL JOIN (SELECT DISTINCT ASIGNATURA_ID
FROM CURSO
NATURAL JOIN ASIGNATURA
WHERE NOMBRE='BASES DE DATOS' AND SEMESTRE_ID = 1);
/*Ejercicio 3.a*/
SELECT NOMBRE, NUM_EXAMEN
FROM ESTUDIANTE
FULL OUTER JOIN ESTUDIANTE_EXTRAORDINARIO ON ESTUDIANTE.ESTUDIANTE_ID = ESTUDIANTE_EXTRAORDINARIO.ESTUDIANTE_ID
FULL OUTER JOIN PLAN_ESTUDIOS ON ESTUDIANTE.PLAN_ESTUDIOS_ID = PLAN_ESTUDIOS.PLAN_ESTUDIOS_ID
WHERE ESTUDIANTE.PLAN_ESTUDIOS_ID = 2;
/*Ejercicio 3.b*/
SELECT PROFESOR.NOMBRE, PROFESOR.APELLIDO_PATERNO, PROFESOR.APELLIDO_MATERNO, CURSO.CLAVE_GRUPO
FROM PROFESOR
FULL OUTER JOIN CURSO ON CURSO.PROFESOR_ID = PROFESOR.PROFESOR_ID WHERE EXISTS (
SELECT CURSO.CLAVE_GRUPO, ASIGNATURA.NOMBRE 
FROM CURSO 
FULL OUTER JOIN ASIGNATURA ON CURSO.ASIGNATURA_ID = ASIGNATURA.ASIGNATURA_ID
FULL OUTER JOIN SEMESTRE ON SEMESTRE.SEMESTRE_ID = CURSO.SEMESTRE_ID);
/*Ejercicio 4.a*/
SELECT A.NOMBRE, A.CREDITOS, A.PLAN_ESTUDIOS_ID, B.NOMBRE AS ASIGNATURA_REQUERIDA
FROM ASIGNATURA A, ASIGNATURA B
WHERE A.CREDITOS = 8 AND A.ASIGNATURA_REQUERIDA_ID = B.ASIGNATURA_ID
UNION ( SELECT NOMBRE, CREDITOS, PLAN_ESTUDIOS_ID, NULL
FROM ASIGNATURA
WHERE CREDITOS = 8
MINUS SELECT A.NOMBRE, A.CREDITOS, A.PLAN_ESTUDIOS_ID, NULL
FROM ASIGNATURA A
WHERE CREDITOS = 8 AND EXISTS(SELECT NOMBRE FROM ASIGNATURA B WHERE A.CREDITOS=8 AND A.ASIGNATURA_REQUERIDA_ID=B.ASIGNATURA_ID) );
/*Ejercicio 5.a*/
SELECT * FROM PLAN_ESTUDIOS CROSS JOIN HORARIO;
/*Ejercicios de Subconsultas:
Ejercicio 1.a*/
SELECT NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, FECHA_NACIMIENTO, (SYSDATE-FECHA_NACIMIENTO)/365.25 AS EDAD, 'EDAD_PROM' AS EDAD_PROM, (SELECT AVG((SYSDATE-FECHA_NACIMIENTO)/365.25) FROM ESTUDIANTE)
FROM ESTUDIANTE;
/*Ejercicio 2.a*/
SELECT ASIGNATURA.NOMBRE, CURSO.CLAVE_GRUPO, PROFESOR.NOMBRE, PROFESOR.APELLIDO_PATERNO, PROFESOR.APELLIDO_MATERNO, PROFESOR.FECHA_NACIMIENTO
FROM PROFESOR
INNER JOIN CURSO ON PROFESOR.PROFESOR_ID = CURSO.PROFESOR_ID
INNER JOIN ASIGNATURA ON CURSO.ASIGNATURA_ID = ASIGNATURA.ASIGNATURA_ID
WHERE FECHA_NACIMIENTO IN (SELECT FECHA_NACIMIENTO
FROM (SELECT FECHA_NACIMIENTO FROM PROFESOR NATURAL JOIN CURSO GROUP BY FECHA_NACIMIENTO ORDER BY 1 DESC)
WHERE ROWNUM <= 1);
/*Ejercicio 3.a*/
SELECT NOMBRE, COUNT(NOMBRE) AS NUM_CURSOS
FROM (SELECT * FROM ASIGNATURA NATURAL JOIN CURSO) 
GROUP BY NOMBRE 
HAVING COUNT(*) > 3;
